name: Validate PR Template Checkboxes

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]
#    branches: [ PreRelease, main, develop, dev, test, test2, stage, prod ]

jobs:
  validate-required-checkboxes:
    runs-on: ubuntu-latest
    steps:
      - name: Check 'types of changes' checkboxes
        uses: tim-actions/check-pr-description-checkbox@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkboxPattern: "- \\[x\\]"
          minChecked: 1
          checkboxSectionHeader: "## Types of changes"

      - name: Check 'Details of changes' checkboxes
        uses: tim-actions/check-pr-description-checkbox@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkboxPattern: "- \\[x\\]"
          minChecked: 1
          checkboxSectionHeader: "## Details of changes"

      - name: Check 'Dev Checklist' checkboxes
        uses: tim-actions/check-pr-description-checkbox@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkboxPattern: "- \\[x\\]"
          minChecked: 10
          checkboxSectionHeader: "## Dev Checklist"

      - name: Check 'APIM Update?' checkboxes
        uses: tim-actions/check-pr-description-checkbox@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkboxPattern: "- \\[x\\]"
          minChecked: 1
          checkboxSectionHeader: "## This Change Needs APIM Update?"

      - name: Check 'Pipeline' checkboxes
        uses: tim-actions/check-pr-description-checkbox@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkboxPattern: "- \\[x\\]"
          minChecked: 3
          checkboxSectionHeader: "## Pipeline"

      - name: Check 'Deployment labels added' checkboxes
        uses: tim-actions/check-pr-description-checkbox@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkboxPattern: "- \\[x\\]"
          minChecked: 1
          checkboxSectionHeader: "## Deployment labels added"




